# Generated by Django 3.1 on 2020-08-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка автомобиля')),
                ('model', models.CharField(max_length=200, verbose_name='Модель автомобиля')),
                ('year_of_issue', models.DateField(verbose_name='Дата выпуска')),
                ('vin', models.CharField(max_length=200, verbose_name='VIN')),
                ('description', models.TextField(verbose_name='Описание автомобиля')),
                ('amount', models.IntegerField(verbose_name='Количество доступных автомобилей')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='AutoKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид автомобиля')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='AutoMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('Рассмотренно', 'Рассмотренно'), ('Не рассмотренно', 'Не рассмотренно')], max_length=30, verbose_name='Статус')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.autokind'),
        ),
        migrations.AddField(
            model_name='auto',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.automark'),
        ),
        migrations.CreateModel(
            name='AccountingCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Машина у клиента', 'Машина у клиента'), ('Машина в гараже', 'Машина в гараже')], max_length=100, verbose_name='Статус')),
                ('zayavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.zayavka')),
            ],
            options={
                'verbose_name': 'Учет',
                'verbose_name_plural': 'Учеты',
            },
        ),
    ]
